-- Migration: 0000_init_tables
-- Generated by drizzle-kit from packages/core/src/db/schema.ts
-- This file is the canonical DDL for the Aprumo ledger v0.1 tables.
-- DO NOT EDIT after applying — drift check in CI (Plan 09) hashes this file.
--
-- v0.5 column reservations in this migration:
--   account_balance.pending_balance  (BIGINT NULL): Reserved for v0.5 pending balance tracking.
--                                     Populated by balance worker. NULL in v0.1.
--   account_balance.available_balance (BIGINT NULL): Reserved for v0.5 available balance tracking.
--                                      Populated by balance worker. NULL in v0.1.

CREATE TABLE "account_balance" (
	"account_id" uuid PRIMARY KEY NOT NULL,
	"balance" bigint DEFAULT 0 NOT NULL,
	"last_posting_id" uuid,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"pending_balance" bigint,
	"available_balance" bigint
);
--> statement-breakpoint
CREATE TABLE "accounts" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"type" text NOT NULL,
	"metadata" jsonb,
	"owner_ref" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "account_type_check" CHECK ("accounts"."type" IN ('asset', 'liability', 'revenue', 'expense', 'equity'))
);
--> statement-breakpoint
CREATE TABLE "accounts_audit" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"table_name" text NOT NULL,
	"operation" text NOT NULL,
	"old_data" jsonb,
	"new_data" jsonb,
	"changed_by" text NOT NULL,
	"changed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "outbound_endpoints" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"customer_id" text NOT NULL,
	"url" text NOT NULL,
	"secret_hash" text NOT NULL,
	"active" boolean DEFAULT true NOT NULL,
	"event_types" jsonb,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "outbound_endpoints_audit" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"table_name" text NOT NULL,
	"operation" text NOT NULL,
	"old_data" jsonb,
	"new_data" jsonb,
	"changed_by" text NOT NULL,
	"changed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "outbound_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"endpoint_id" uuid NOT NULL,
	"type" text NOT NULL,
	"payload_jsonb" jsonb NOT NULL,
	"status" text DEFAULT 'pending' NOT NULL,
	"attempts" bigint DEFAULT 0 NOT NULL,
	"last_error" text,
	"next_attempt_at" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "outbound_events_audit" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"table_name" text NOT NULL,
	"operation" text NOT NULL,
	"old_data" jsonb,
	"new_data" jsonb,
	"changed_by" text NOT NULL,
	"changed_at" timestamp with time zone DEFAULT now() NOT NULL
);
--> statement-breakpoint
CREATE TABLE "postings" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"transaction_id" uuid NOT NULL,
	"account_id" uuid NOT NULL,
	"amount_cents" bigint NOT NULL,
	"direction" text NOT NULL,
	CONSTRAINT "posting_direction_check" CHECK ("postings"."direction" IN ('debit', 'credit'))
);
--> statement-breakpoint
CREATE TABLE "raw_events" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"provider" text NOT NULL,
	"provider_event_id" text NOT NULL,
	"received_at" timestamp with time zone DEFAULT now() NOT NULL,
	"payload_jsonb" jsonb NOT NULL,
	"transaction_id" uuid,
	"status" text DEFAULT 'pending' NOT NULL,
	CONSTRAINT "raw_events_provider_event_id_unique" UNIQUE("provider","provider_event_id"),
	CONSTRAINT "raw_event_status_check" CHECK ("raw_events"."status" IN ('pending', 'reconciled', 'failed'))
);
--> statement-breakpoint
CREATE TABLE "transactions" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"idempotency_key" text NOT NULL,
	"ts" timestamp with time zone DEFAULT now() NOT NULL,
	"description" text,
	"source" text,
	"metadata" jsonb,
	CONSTRAINT "transactions_idempotency_key_unique" UNIQUE("idempotency_key")
);
--> statement-breakpoint
ALTER TABLE "account_balance" ADD CONSTRAINT "account_balance_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "outbound_events" ADD CONSTRAINT "outbound_events_endpoint_id_outbound_endpoints_id_fk" FOREIGN KEY ("endpoint_id") REFERENCES "public"."outbound_endpoints"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "postings" ADD CONSTRAINT "postings_transaction_id_transactions_id_fk" FOREIGN KEY ("transaction_id") REFERENCES "public"."transactions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "postings" ADD CONSTRAINT "postings_account_id_accounts_id_fk" FOREIGN KEY ("account_id") REFERENCES "public"."accounts"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
ALTER TABLE "raw_events" ADD CONSTRAINT "raw_events_transaction_id_transactions_id_fk" FOREIGN KEY ("transaction_id") REFERENCES "public"."transactions"("id") ON DELETE no action ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "postings_transaction_id_idx" ON "postings" USING btree ("transaction_id");--> statement-breakpoint
CREATE INDEX "raw_events_provider_idx" ON "raw_events" USING btree ("provider");--> statement-breakpoint
CREATE INDEX "raw_events_status_idx" ON "raw_events" USING btree ("status");
--> statement-breakpoint
-- v0.5 reservation comments (D-47): document columns reserved for future use
COMMENT ON COLUMN account_balance.pending_balance IS 'Reserved for v0.5 pending balance tracking; populated by balance worker, NULL in v0.1.';
COMMENT ON COLUMN account_balance.available_balance IS 'Reserved for v0.5 available balance tracking; populated by balance worker, NULL in v0.1.';